### ISSUE TITLE
Invitation request

### ISSUE THREAD

**Issue by GunterMueller** [LM-3/-read-.-this-#16]
Hello,
I would like to join. I'm fascinated with  Lisp and Lisp Machines since my Highschool and my first semester introduction into Lisp Programming .
I actually tried to read  Christian-Michael Hamann (Author) - Einführung in das Programmieren in LISP (German) as a Highschool student without access to any Lisp system,
( Yes, I'm German and was educated in Germany. Actually kind of close to Worms, where Sebastian lives. Greetings!
Thanks,
  Gunter

**Comment by ams** [comment]
Hi! I've sent you an invitation request! Welcome, and happy hacking!
