### ISSUE TITLE
Explainable Artificial Intelligence

### ISSUE THREAD

**Issue by wpasieka** [LM-3/-read-.-this-#17]
This is a general information, to join the group.

All links below are my personal work, and there are to lead to the LEO-6G, with the Lisp as an unified environment, including the Chaosnet  as a new space standard:

http://www.pressitoncloud.com/CMUCL_Cyber_Security_Artificial_Intelligence_Conference_en_EN.html

http://www.pressitoncloud.com/PressAI_LEO_Quantum_Communication_en_EN.html

http://www.pressitoncloud.com/Pressiton_University_en_EN.html

;;------------------------------
To make a progress, we would need a real Lisp machine in Poland, which can work with the LM-3 and the finance for a further development from the EU, which shall be available.

Please let me know Your thoughts, maybe there are some better ways.

Adrian W. Pasieka Ikane.

**Comment by ams** [comment]
Witam pana do grupy!
