### ISSUE TITLE
Remote tape backups

### ISSUE THREAD

**Issue by larsbrinkhoff** [LM-3/-read-.-this-#7]
There's an RTAPE Chaosnet service for remote tape access.

ITS can use it to make backups.  But I don't have any RTAPE server.

- Is there an RTAPE Chaosnet server?  For Lisp machines or Unix?
- Is there an RTAPE TCP/IP server?  Symbolics used to distribute one for BSD Unix.

**Comment by ams** [comment]
See the chaos repository, branch ams/next.  There, there is a RTAPE server.

I am unsure about one for TCP/IP, there is a TCP service that takes Chaos and sends it over TCP or some such.

**Comment by ams** [comment]
The RTAPE service talks directly to a tape device, not a file so that would need to be hacked just a bit.

**Comment by ams** [comment]
And Here is the file: https://github.com/LM-3/chaos/blob/ams/next/cmd/RTAPE.c

**Comment by larsbrinkhoff** [comment]
Thanks!  This looks good.

**Comment by ams** [comment]
Sorry, thought it was still open.  Sighs.
