### ISSUE TITLE
Request for a invitation.

### ISSUE THREAD

**Issue by yvm** [LM-3/-read-.-this-#8]
Hi.
I have Altera's Cyclone V, AD/DA Data Conversion cards, a bit of enthusiasm (my knowledge of HDLs is very common, proprietary IDEs and IP-cores feels horrible, but I like the idea of re-implementing MIT CADR on modern hardware very much).
In the subject my main goal is a LISP-machine able to introspect at least up to RTL.

**Comment by ams** [comment]
Hi! Welcome, and happy hacking.

What are you thinking when you say “reimplementing the MIT CADR on modern hardware”?

The HDL is based on the original schematics, so there is little modernity on that side at least.
