### ISSUE TITLE
Request for invitation

### ISSUE THREAD

**Issue by luksamuk** [LM-3/-read-.-this-#9]
Hello, I'm a member of [Common Lisp Brazil](https://github.com/commonlispbr) and I'm very interested in joining the group. The idea of having a viable LM these days is fascinating, and I was wondering if I could build one myself, or at least help make building one possible.

**Comment by ams** [comment]
Hi! I sent you an invite.

I am not sure what a viable Lisp Machine would be today though.  One would be to clarify what is a Lisp Machine.   E.g. is Mezzano a lisp machine? IMHO it is.

LM-3 is more about preserving an existing environment and allowing it to continue to run many years later.  Plus, it’s fun. :-)

If you have any question feel free to ask! And welcome.

**Comment by luksamuk** [comment]
Sorry for taking a month to answer!
I don't think "viable" was a good choice of words. What I meant is that I wanted to actually build a LM from scratch, using standalone hardware -- specially using an embedded device --, probably under RISC-V. For now, I'm trying to experiment with building a simple kernel for the RPi3.

**Comment by ams** [comment]
The goal of this project is restoring the MIT CADR which was the 2nd Lisp Machine.  It already runs on "standalone" hardware, using FPGA and other bits and bobs.   And simulated as well.
